# Display time
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_12HR=true
SPACESHIP_TIME_FORMAT="%D{%a %d %I:%M}"

# Battery
SPACESHIP_BATTERY_THRESHOLD=25

# Bun
SPACESHIP_BUN_SYMBOL="🍔 "
SPACESHIP_BUN_COLOR=#ffbb52
